import os
import uuid

MUSE_LOAD_TESTING = os.environ.get("MUSE_LOAD_TESTING", False)
INFERENCE_REQUEST_TIMEOUT = os.environ.get("INFERENCE_REQUEST_TIMEOUT", 160)
KEEP_ALIVE_TIMEOUT = os.environ.get("KEEP_ALIVE_TIMEOUT", 160)
RATE_LIMIT_KEY = os.environ.get("RATE_LIMIT_KEY", str(uuid.uuid4().hex))
SENTRY_API_KEY = os.environ.get("SENTRY_API_KEY", None)
IMAGE_SIZE = 512

NSFW_PROMPTS = [
    "anal",
    "anus",
    "ass",
    "asshole",
    "ball licking",
    "ball sack",
    "ball sucking",
    "bangbros",
    "bastard",
    "bbw",
    "bdsm",
    "big black",
    "big breasts",
    "bitch",
    "blow job",
    "boner",
    "boob",
    "bullshit",
    "butt",
    "butthole",
    "cock",
    "creampie",
    "cum",
    "cunt",
    "dick",
    "dildo",
    "doggy style",
    "ejaculation",
    "erotic",
    "escort",
    "fingering",
    "fuck",
    "gangbang",
    "gang bang",
    "genitals",
    "grope",
    "group sex",
    "g-spot",
    "handjob",
    "hardcore",
    "hentai",
    "hooker",
    "horny",
    "hot chick",
    "jerk off",
    "juggs",
    "kinky",
    "masturbate",
    "masturbating",
    "milf",
    "motherfucker",
    "nigga",
    "nipples",
    "nsfw",
    "nude",
    "nudity",
    "orgasm",
    "orgy",
    "panty",
    "penis",
    "porn",
    "porno",
    "pornography",
    "pubes",
    "pussy",
    "rapist",
    "rectum",
    "sexuality",
    "shaved pussy",
    "shit",
    "slut",
    "splooge moose",
    "spread legs",
    "strip club",
    "style doggy",
    "sucks",
    "sultry women",
    "swastika",
    "threesome",
    "throating",
    "tits",
    "titties",
    "topless",
    "undressing",
    "upskirt",
    "urethra play",
    "vagina",
    "viagra",
    "vibrator",
    "wet dream",
    "whore",
    "worldsex",
    "xxx",
]
